apiVersion: v1
kind: Service
metadata:
  name: verdyx-frontend-service
  namespace: verdyx
  labels:
    app: verdyx-frontend
    component: frontend
    service: web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: verdyx-frontend
  sessionAffinity: None

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: verdyx-frontend-sa
  namespace: verdyx
  labels:
    app: verdyx-frontend
    component: frontend
