apiVersion: v1
kind: Service
metadata:
  name: analysis-engine-service
  namespace: nexus-security
  labels:
    app: analysis-engine
    component: backend
    service: analysis
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: analysis-engine
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: analysis-engine-headless
  namespace: nexus-security
  labels:
    app: analysis-engine
    component: backend
    service: analysis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: analysis-engine

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analysis-engine-sa
  namespace: nexus-security
  labels:
    app: analysis-engine
    component: backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: analysis-engine-role
  namespace: nexus-security
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analysis-engine-rolebinding
  namespace: nexus-security
subjects:
- kind: ServiceAccount
  name: analysis-engine-sa
  namespace: nexus-security
roleRef:
  kind: Role
  name: analysis-engine-role
  apiGroup: rbac.authorization.k8s.io