import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, FileJson, FileText, Share2, Printer } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ExportReportProps {
  submissionId: string;
  fileName: string;
  consensus?: any;
  analyses?: any[];
}

export function ExportReport({ submissionId, fileName, consensus, analyses = [] }: ExportReportProps) {
  const { toast } = useToast();

  const exportAsJSON = () => {
    try {
      const reportData = {
        submissionId,
        fileName,
        exportedAt: new Date().toISOString(),
        consensus: consensus || null,
        analyses: analyses.map((analysis: any) => ({
          engineId: analysis.engineId,
          engineName: analysis.engine?.name,
          verdict: analysis.verdict,
          confidence: analysis.confidence,
          status: analysis.status,
          stakeAmount: analysis.stakeAmount,
          completedAt: analysis.completedAt,
        })),
        summary: {
          totalEngines: analyses.length,
          completedAnalyses: analyses.filter((a: any) => a.status === "completed").length,
          finalVerdict: consensus?.finalVerdict || "pending",
          confidenceScore: consensus?.confidenceScore || "0",
        },
      };

      const dataStr = JSON.stringify(reportData, null, 2);
      const dataBlob = new Blob([dataStr], { type: "application/json" });
      const url = URL.createObjectURL(dataBlob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `nexus-report-${submissionId}-${Date.now()}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Export Successful",
        description: (
          <div className="flex items-center gap-2">
            <FileJson className="h-4 w-4 text-green-500 flex-shrink-0" />
            <span>Report exported as JSON</span>
          </div>
        ),
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Failed to export report as JSON",
        variant: "destructive",
      });
    }
  };

  const exportAsMarkdown = () => {
    try {
      let markdown = `# Nexus Security Analysis Report\n\n`;
      markdown += `**File:** ${fileName}\n`;
      markdown += `**Submission ID:** ${submissionId}\n`;
      markdown += `**Generated:** ${new Date().toLocaleString()}\n\n`;

      if (consensus) {
        markdown += `## Consensus Result\n\n`;
        markdown += `- **Final Verdict:** ${consensus.finalVerdict}\n`;
        markdown += `- **Confidence Score:** ${consensus.confidenceScore}%\n`;
        markdown += `- **Total Engines:** ${consensus.totalEngines}\n`;
        markdown += `- **Malicious Votes:** ${consensus.maliciousVotes}\n`;
        markdown += `- **Suspicious Votes:** ${consensus.suspiciousVotes}\n`;
        markdown += `- **Clean Votes:** ${consensus.cleanVotes}\n\n`;
      }

      if (analyses.length > 0) {
        markdown += `## Individual Engine Analysis\n\n`;
        markdown += `| Engine | Verdict | Confidence | Status | Stake |\n`;
        markdown += `|--------|---------|------------|--------|-------|\n`;

        analyses.forEach((analysis: any) => {
          markdown += `| ${analysis.engine?.name || "Unknown"} | ${analysis.verdict || "Pending"} | ${analysis.confidence || "N/A"}% | ${analysis.status} | ${analysis.stakeAmount} ETH |\n`;
        });
      }

      markdown += `\n---\n\n`;
      markdown += `*Generated by Nexus Security Platform*\n`;

      const dataBlob = new Blob([markdown], { type: "text/markdown" });
      const url = URL.createObjectURL(dataBlob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `nexus-report-${submissionId}-${Date.now()}.md`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Export Successful",
        description: (
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-green-500 flex-shrink-0" />
            <span>Report exported as Markdown</span>
          </div>
        ),
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Failed to export report as Markdown",
        variant: "destructive",
      });
    }
  };

  const exportAsCSV = () => {
    try {
      let csv = "Engine Name,Verdict,Confidence,Status,Stake Amount,Completed At\n";

      analyses.forEach((analysis: any) => {
        csv += `"${analysis.engine?.name || "Unknown"}",`;
        csv += `"${analysis.verdict || "Pending"}",`;
        csv += `"${analysis.confidence || "N/A"}",`;
        csv += `"${analysis.status}",`;
        csv += `"${analysis.stakeAmount}",`;
        csv += `"${analysis.completedAt ? new Date(analysis.completedAt).toLocaleString() : "N/A"}"\n`;
      });

      const dataBlob = new Blob([csv], { type: "text/csv" });
      const url = URL.createObjectURL(dataBlob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `nexus-analysis-${submissionId}-${Date.now()}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Export Successful",
        description: (
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-green-500 flex-shrink-0" />
            <span>Analysis data exported as CSV</span>
          </div>
        ),
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Failed to export as CSV",
        variant: "destructive",
      });
    }
  };

  const copyShareLink = () => {
    const shareUrl = `${window.location.origin}/analysis/${submissionId}`;
    navigator.clipboard.writeText(shareUrl).then(() => {
      toast({
        title: "Link Copied!",
        description: (
          <div className="flex items-center gap-2">
            <Share2 className="h-4 w-4 text-green-500 flex-shrink-0" />
            <span>Share link copied to clipboard</span>
          </div>
        ),
      });
    }).catch(() => {
      toast({
        title: "Copy Failed",
        description: "Failed to copy share link",
        variant: "destructive",
      });
    });
  };

  const printReport = () => {
    window.print();
    toast({
      title: "Print Dialog Opened",
      description: (
        <div className="flex items-center gap-2">
          <Printer className="h-4 w-4 text-primary flex-shrink-0" />
          <span>Print dialog has been opened</span>
        </div>
      ),
    });
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Download className="h-4 w-4" />
          Export Report
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel>Export Options</DropdownMenuLabel>
        <DropdownMenuSeparator />

        <DropdownMenuItem onClick={exportAsJSON} className="gap-2">
          <FileJson className="h-4 w-4" />
          <span>Export as JSON</span>
        </DropdownMenuItem>

        <DropdownMenuItem onClick={exportAsMarkdown} className="gap-2">
          <FileText className="h-4 w-4" />
          <span>Export as Markdown</span>
        </DropdownMenuItem>

        <DropdownMenuItem onClick={exportAsCSV} className="gap-2">
          <FileText className="h-4 w-4" />
          <span>Export Analysis (CSV)</span>
        </DropdownMenuItem>

        <DropdownMenuSeparator />

        <DropdownMenuItem onClick={copyShareLink} className="gap-2">
          <Share2 className="h-4 w-4" />
          <span>Copy Share Link</span>
        </DropdownMenuItem>

        <DropdownMenuItem onClick={printReport} className="gap-2">
          <Printer className="h-4 w-4" />
          <span>Print Report</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
