/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationSystem,
  IReputationSystemInterface,
} from "../../../contracts/Interfaces/IReputationSystem";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "penaltyAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "EnginePenalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "engineType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "initialReputation",
        type: "uint256",
      },
    ],
    name: "EngineRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "EngineRewarded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "decayAmount",
        type: "uint256",
      },
    ],
    name: "ReputationDecayed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldReputation",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newReputation",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "ReputationUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
    ],
    name: "applyReputationDecay",
    outputs: [
      {
        internalType: "uint256",
        name: "newReputation",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "baseStake",
        type: "uint256",
      },
    ],
    name: "calculateRequiredStake",
    outputs: [
      {
        internalType: "uint256",
        name: "requiredStake",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
    ],
    name: "deactivateEngine",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
    ],
    name: "getAccuracyRate",
    outputs: [
      {
        internalType: "uint256",
        name: "accuracyRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDecayParameters",
    outputs: [
      {
        internalType: "uint256",
        name: "decayRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "decayPeriod",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "engineType",
        type: "uint8",
      },
    ],
    name: "getEngineMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "multiplier",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMinimumReputation",
    outputs: [
      {
        internalType: "uint256",
        name: "minReputation",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
    ],
    name: "getReputation",
    outputs: [
      {
        internalType: "uint256",
        name: "reputation",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getReputationHistory",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "oldReputation",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "newReputation",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "changeType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "bountyId",
            type: "uint256",
          },
        ],
        internalType: "struct IReputationSystem.ReputationRecord[]",
        name: "records",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getTopEngines",
    outputs: [
      {
        internalType: "address[]",
        name: "engines",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "reputations",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
    ],
    name: "isEligibleEngine",
    outputs: [
      {
        internalType: "bool",
        name: "eligible",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "penaltyAmount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "penalizeEngine",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
    ],
    name: "reactivateEngine",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "engineType",
        type: "uint8",
      },
    ],
    name: "registerEngine",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "engineAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "wasCorrect",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "stakeAmount",
        type: "uint256",
      },
    ],
    name: "updateReputationForAnalysis",
    outputs: [
      {
        internalType: "uint256",
        name: "newReputation",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationSystem__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationSystemInterface {
    return new Interface(_abi) as IReputationSystemInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationSystem {
    return new Contract(address, _abi, runner) as unknown as IReputationSystem;
  }
}
