/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBountyManager } from "./IBountyManager";
export type { IReputationSystem } from "./IReputationSystem";
export type { IThreatToken } from "./IThreatToken";
