/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IReputationSystem {
  export type ReputationRecordStruct = {
    timestamp: BigNumberish;
    oldReputation: BigNumberish;
    newReputation: BigNumberish;
    changeType: BigNumberish;
    bountyId: BigNumberish;
  };

  export type ReputationRecordStructOutput = [
    timestamp: bigint,
    oldReputation: bigint,
    newReputation: bigint,
    changeType: bigint,
    bountyId: bigint
  ] & {
    timestamp: bigint;
    oldReputation: bigint;
    newReputation: bigint;
    changeType: bigint;
    bountyId: bigint;
  };
}

export interface IReputationSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyReputationDecay"
      | "calculateRequiredStake"
      | "deactivateEngine"
      | "getAccuracyRate"
      | "getDecayParameters"
      | "getEngineMultiplier"
      | "getMinimumReputation"
      | "getReputation"
      | "getReputationHistory"
      | "getTopEngines"
      | "isEligibleEngine"
      | "penalizeEngine"
      | "reactivateEngine"
      | "registerEngine"
      | "updateReputationForAnalysis"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EnginePenalized"
      | "EngineRegistered"
      | "EngineRewarded"
      | "ReputationDecayed"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applyReputationDecay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredStake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccuracyRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecayParameters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumReputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopEngines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "penalizeEngine",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEngine",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputationForAnalysis",
    values: [AddressLike, BigNumberish, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "applyReputationDecay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccuracyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecayParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopEngines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "penalizeEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputationForAnalysis",
    data: BytesLike
  ): Result;
}

export namespace EnginePenalizedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    penaltyAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    engineAddress: string,
    penaltyAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    engineAddress: string;
    penaltyAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EngineRegisteredEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    engineType: BigNumberish,
    initialReputation: BigNumberish
  ];
  export type OutputTuple = [
    engineAddress: string,
    engineType: bigint,
    initialReputation: bigint
  ];
  export interface OutputObject {
    engineAddress: string;
    engineType: bigint;
    initialReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EngineRewardedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    rewardAmount: BigNumberish,
    bountyId: BigNumberish
  ];
  export type OutputTuple = [
    engineAddress: string,
    rewardAmount: bigint,
    bountyId: bigint
  ];
  export interface OutputObject {
    engineAddress: string;
    rewardAmount: bigint;
    bountyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationDecayedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    decayAmount: BigNumberish
  ];
  export type OutputTuple = [engineAddress: string, decayAmount: bigint];
  export interface OutputObject {
    engineAddress: string;
    decayAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    oldReputation: BigNumberish,
    newReputation: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    engineAddress: string,
    oldReputation: bigint,
    newReputation: bigint,
    reason: string
  ];
  export interface OutputObject {
    engineAddress: string;
    oldReputation: bigint;
    newReputation: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IReputationSystem extends BaseContract {
  connect(runner?: ContractRunner | null): IReputationSystem;
  waitForDeployment(): Promise<this>;

  interface: IReputationSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyReputationDecay: TypedContractMethod<
    [engineAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;

  calculateRequiredStake: TypedContractMethod<
    [engineAddress: AddressLike, baseStake: BigNumberish],
    [bigint],
    "view"
  >;

  deactivateEngine: TypedContractMethod<
    [engineAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getAccuracyRate: TypedContractMethod<
    [engineAddress: AddressLike],
    [bigint],
    "view"
  >;

  getDecayParameters: TypedContractMethod<
    [],
    [[bigint, bigint] & { decayRate: bigint; decayPeriod: bigint }],
    "view"
  >;

  getEngineMultiplier: TypedContractMethod<
    [engineType: BigNumberish],
    [bigint],
    "view"
  >;

  getMinimumReputation: TypedContractMethod<[], [bigint], "view">;

  getReputation: TypedContractMethod<
    [engineAddress: AddressLike],
    [bigint],
    "view"
  >;

  getReputationHistory: TypedContractMethod<
    [engineAddress: AddressLike, limit: BigNumberish],
    [IReputationSystem.ReputationRecordStructOutput[]],
    "view"
  >;

  getTopEngines: TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { engines: string[]; reputations: bigint[] }],
    "view"
  >;

  isEligibleEngine: TypedContractMethod<
    [engineAddress: AddressLike],
    [boolean],
    "view"
  >;

  penalizeEngine: TypedContractMethod<
    [engineAddress: AddressLike, penaltyAmount: BigNumberish, reason: string],
    [boolean],
    "nonpayable"
  >;

  reactivateEngine: TypedContractMethod<
    [engineAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  registerEngine: TypedContractMethod<
    [engineAddress: AddressLike, engineType: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  updateReputationForAnalysis: TypedContractMethod<
    [
      engineAddress: AddressLike,
      bountyId: BigNumberish,
      wasCorrect: boolean,
      stakeAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyReputationDecay"
  ): TypedContractMethod<[engineAddress: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateRequiredStake"
  ): TypedContractMethod<
    [engineAddress: AddressLike, baseStake: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateEngine"
  ): TypedContractMethod<[engineAddress: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getAccuracyRate"
  ): TypedContractMethod<[engineAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDecayParameters"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { decayRate: bigint; decayPeriod: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEngineMultiplier"
  ): TypedContractMethod<[engineType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinimumReputation"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[engineAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationHistory"
  ): TypedContractMethod<
    [engineAddress: AddressLike, limit: BigNumberish],
    [IReputationSystem.ReputationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopEngines"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { engines: string[]; reputations: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEligibleEngine"
  ): TypedContractMethod<[engineAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "penalizeEngine"
  ): TypedContractMethod<
    [engineAddress: AddressLike, penaltyAmount: BigNumberish, reason: string],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reactivateEngine"
  ): TypedContractMethod<[engineAddress: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "registerEngine"
  ): TypedContractMethod<
    [engineAddress: AddressLike, engineType: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputationForAnalysis"
  ): TypedContractMethod<
    [
      engineAddress: AddressLike,
      bountyId: BigNumberish,
      wasCorrect: boolean,
      stakeAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "EnginePenalized"
  ): TypedContractEvent<
    EnginePenalizedEvent.InputTuple,
    EnginePenalizedEvent.OutputTuple,
    EnginePenalizedEvent.OutputObject
  >;
  getEvent(
    key: "EngineRegistered"
  ): TypedContractEvent<
    EngineRegisteredEvent.InputTuple,
    EngineRegisteredEvent.OutputTuple,
    EngineRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EngineRewarded"
  ): TypedContractEvent<
    EngineRewardedEvent.InputTuple,
    EngineRewardedEvent.OutputTuple,
    EngineRewardedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationDecayed"
  ): TypedContractEvent<
    ReputationDecayedEvent.InputTuple,
    ReputationDecayedEvent.OutputTuple,
    ReputationDecayedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "EnginePenalized(address,uint256,string)": TypedContractEvent<
      EnginePenalizedEvent.InputTuple,
      EnginePenalizedEvent.OutputTuple,
      EnginePenalizedEvent.OutputObject
    >;
    EnginePenalized: TypedContractEvent<
      EnginePenalizedEvent.InputTuple,
      EnginePenalizedEvent.OutputTuple,
      EnginePenalizedEvent.OutputObject
    >;

    "EngineRegistered(address,uint8,uint256)": TypedContractEvent<
      EngineRegisteredEvent.InputTuple,
      EngineRegisteredEvent.OutputTuple,
      EngineRegisteredEvent.OutputObject
    >;
    EngineRegistered: TypedContractEvent<
      EngineRegisteredEvent.InputTuple,
      EngineRegisteredEvent.OutputTuple,
      EngineRegisteredEvent.OutputObject
    >;

    "EngineRewarded(address,uint256,uint256)": TypedContractEvent<
      EngineRewardedEvent.InputTuple,
      EngineRewardedEvent.OutputTuple,
      EngineRewardedEvent.OutputObject
    >;
    EngineRewarded: TypedContractEvent<
      EngineRewardedEvent.InputTuple,
      EngineRewardedEvent.OutputTuple,
      EngineRewardedEvent.OutputObject
    >;

    "ReputationDecayed(address,uint256)": TypedContractEvent<
      ReputationDecayedEvent.InputTuple,
      ReputationDecayedEvent.OutputTuple,
      ReputationDecayedEvent.OutputObject
    >;
    ReputationDecayed: TypedContractEvent<
      ReputationDecayedEvent.InputTuple,
      ReputationDecayedEvent.OutputTuple,
      ReputationDecayedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256,string)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
