/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IReputationSystem {
  export type EngineInfoStruct = {
    isRegistered: boolean;
    engineType: BigNumberish;
    reputation: BigNumberish;
    totalAnalyses: BigNumberish;
    correctAnalyses: BigNumberish;
    lastActivityTimestamp: BigNumberish;
    registrationTimestamp: BigNumberish;
    isActive: boolean;
  };

  export type EngineInfoStructOutput = [
    isRegistered: boolean,
    engineType: bigint,
    reputation: bigint,
    totalAnalyses: bigint,
    correctAnalyses: bigint,
    lastActivityTimestamp: bigint,
    registrationTimestamp: bigint,
    isActive: boolean
  ] & {
    isRegistered: boolean;
    engineType: bigint;
    reputation: bigint;
    totalAnalyses: bigint;
    correctAnalyses: bigint;
    lastActivityTimestamp: bigint;
    registrationTimestamp: bigint;
    isActive: boolean;
  };

  export type ReputationRecordStruct = {
    timestamp: BigNumberish;
    oldReputation: BigNumberish;
    newReputation: BigNumberish;
    changeType: BigNumberish;
    bountyId: BigNumberish;
  };

  export type ReputationRecordStructOutput = [
    timestamp: bigint,
    oldReputation: bigint,
    newReputation: bigint,
    changeType: bigint,
    bountyId: bigint
  ] & {
    timestamp: bigint;
    oldReputation: bigint;
    newReputation: bigint;
    changeType: bigint;
    bountyId: bigint;
  };
}

export declare namespace ReputationSystem {
  export type EngineProfileStruct = {
    isRegistered: boolean;
    engineType: BigNumberish;
    reputation: BigNumberish;
    totalSubmissions: BigNumberish;
    correctPredictions: BigNumberish;
    lastActiveTimestamp: BigNumberish;
    registrationTimestamp: BigNumberish;
    isActive: boolean;
    falsePositives: BigNumberish;
    falseNegatives: BigNumberish;
    totalStakeAmount: BigNumberish;
    totalRewards: BigNumberish;
    consecutiveCorrect: BigNumberish;
    maxConsecutiveCorrect: BigNumberish;
  };

  export type EngineProfileStructOutput = [
    isRegistered: boolean,
    engineType: bigint,
    reputation: bigint,
    totalSubmissions: bigint,
    correctPredictions: bigint,
    lastActiveTimestamp: bigint,
    registrationTimestamp: bigint,
    isActive: boolean,
    falsePositives: bigint,
    falseNegatives: bigint,
    totalStakeAmount: bigint,
    totalRewards: bigint,
    consecutiveCorrect: bigint,
    maxConsecutiveCorrect: bigint
  ] & {
    isRegistered: boolean;
    engineType: bigint;
    reputation: bigint;
    totalSubmissions: bigint;
    correctPredictions: bigint;
    lastActiveTimestamp: bigint;
    registrationTimestamp: bigint;
    isActive: boolean;
    falsePositives: bigint;
    falseNegatives: bigint;
    totalStakeAmount: bigint;
    totalRewards: bigint;
    consecutiveCorrect: bigint;
    maxConsecutiveCorrect: bigint;
  };

  export type ReputationTierStruct = {
    minReputation: BigNumberish;
    maxStakeMultiplier: BigNumberish;
    rewardBonus: BigNumberish;
    tierName: string;
  };

  export type ReputationTierStructOutput = [
    minReputation: bigint,
    maxStakeMultiplier: bigint,
    rewardBonus: bigint,
    tierName: string
  ] & {
    minReputation: bigint;
    maxStakeMultiplier: bigint;
    rewardBonus: bigint;
    tierName: string;
  };
}

export interface ReputationSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACCURACY_WEIGHT"
      | "ADMIN_ROLE"
      | "BOUNTY_MANAGER_ROLE"
      | "CONSISTENCY_WEIGHT"
      | "DECAY_RATE"
      | "DEFAULT_ADMIN_ROLE"
      | "INITIAL_REPUTATION"
      | "MAX_REPUTATION"
      | "MIN_REPUTATION"
      | "MIN_SUBMISSIONS_FOR_RATING"
      | "PARTICIPATION_WEIGHT"
      | "activeEngines"
      | "applyReputationDecay"
      | "applyReputationDecayAll"
      | "calculateRequiredStake"
      | "deactivateEngine"
      | "decayTimestamp"
      | "engineIndex"
      | "engineSubmissions"
      | "engines"
      | "getAccuracyRate"
      | "getAnalystTier"
      | "getDecayParameters"
      | "getEngineInfo"
      | "getEngineMultiplier"
      | "getEngineProfile"
      | "getMinimumReputation"
      | "getReputation"
      | "getReputationHistory"
      | "getReputationTier"
      | "getRoleAdmin"
      | "getTopAnalysts"
      | "getTopEngines"
      | "getTotalAnalysts"
      | "grantRole"
      | "hasRole"
      | "isEligibleEngine"
      | "isEligibleForTier"
      | "nextSubmissionId"
      | "penalizeEngine"
      | "reactivateEngine"
      | "recordSubmission"
      | "registerEngine"
      | "renounceRole"
      | "reputationTiers"
      | "resolveSubmission"
      | "revokeRole"
      | "rewardEngine"
      | "submissions"
      | "supportsInterface"
      | "totalActiveEngines"
      | "updateReputation"
      | "updateReputationForAnalysis"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EnginePenalized"
      | "EngineRegistered"
      | "EngineRewarded"
      | "ReputationDecayed"
      | "ReputationUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SubmissionRecorded"
      | "SubmissionResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACCURACY_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BOUNTY_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONSISTENCY_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SUBMISSIONS_FOR_RATING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PARTICIPATION_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeEngines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyReputationDecay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyReputationDecayAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequiredStake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decayTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "engineIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "engineSubmissions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "engines",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccuracyRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnalystTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecayParameters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumReputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopAnalysts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopEngines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAnalysts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleForTier",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSubmissionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "penalizeEngine",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubmission",
    values: [AddressLike, BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEngine",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveSubmission",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEngine",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalActiveEngines",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputationForAnalysis",
    values: [AddressLike, BigNumberish, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCURACY_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BOUNTY_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONSISTENCY_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DECAY_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SUBMISSIONS_FOR_RATING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PARTICIPATION_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeEngines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyReputationDecay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyReputationDecayAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequiredStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decayTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "engineIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "engineSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "engines", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccuracyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnalystTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecayParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopAnalysts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopEngines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAnalysts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleForTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSubmissionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "penalizeEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalActiveEngines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputationForAnalysis",
    data: BytesLike
  ): Result;
}

export namespace EnginePenalizedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    penaltyAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    engineAddress: string,
    penaltyAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    engineAddress: string;
    penaltyAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EngineRegisteredEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    engineType: BigNumberish,
    initialReputation: BigNumberish
  ];
  export type OutputTuple = [
    engineAddress: string,
    engineType: bigint,
    initialReputation: bigint
  ];
  export interface OutputObject {
    engineAddress: string;
    engineType: bigint;
    initialReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EngineRewardedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    rewardAmount: BigNumberish,
    bountyId: BigNumberish
  ];
  export type OutputTuple = [
    engineAddress: string,
    rewardAmount: bigint,
    bountyId: bigint
  ];
  export interface OutputObject {
    engineAddress: string;
    rewardAmount: bigint;
    bountyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationDecayedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    decayAmount: BigNumberish
  ];
  export type OutputTuple = [engineAddress: string, decayAmount: bigint];
  export interface OutputObject {
    engineAddress: string;
    decayAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    engineAddress: AddressLike,
    oldReputation: BigNumberish,
    newReputation: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    engineAddress: string,
    oldReputation: bigint,
    newReputation: bigint,
    reason: string
  ];
  export interface OutputObject {
    engineAddress: string;
    oldReputation: bigint;
    newReputation: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionRecordedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    engineAddress: AddressLike,
    bountyId: BigNumberish,
    prediction: boolean,
    stakeAmount: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: bigint,
    engineAddress: string,
    bountyId: bigint,
    prediction: boolean,
    stakeAmount: bigint
  ];
  export interface OutputObject {
    submissionId: bigint;
    engineAddress: string;
    bountyId: bigint;
    prediction: boolean;
    stakeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionResolvedEvent {
  export type InputTuple = [
    submissionId: BigNumberish,
    isCorrect: boolean,
    reputationChange: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: bigint,
    isCorrect: boolean,
    reputationChange: bigint
  ];
  export interface OutputObject {
    submissionId: bigint;
    isCorrect: boolean;
    reputationChange: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationSystem extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationSystem;
  waitForDeployment(): Promise<this>;

  interface: ReputationSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACCURACY_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BOUNTY_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  CONSISTENCY_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  DECAY_RATE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INITIAL_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MAX_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MIN_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MIN_SUBMISSIONS_FOR_RATING: TypedContractMethod<[], [bigint], "view">;

  PARTICIPATION_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  activeEngines: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  applyReputationDecay: TypedContractMethod<
    [engineAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;

  applyReputationDecayAll: TypedContractMethod<[], [void], "nonpayable">;

  calculateRequiredStake: TypedContractMethod<
    [engineAddress: AddressLike, baseStake: BigNumberish],
    [bigint],
    "view"
  >;

  deactivateEngine: TypedContractMethod<
    [engineAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  decayTimestamp: TypedContractMethod<[], [bigint], "view">;

  engineIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  engineSubmissions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  engines: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isRegistered: boolean;
        engineType: bigint;
        reputation: bigint;
        totalSubmissions: bigint;
        correctPredictions: bigint;
        lastActiveTimestamp: bigint;
        registrationTimestamp: bigint;
        isActive: boolean;
        falsePositives: bigint;
        falseNegatives: bigint;
        totalStakeAmount: bigint;
        totalRewards: bigint;
        consecutiveCorrect: bigint;
        maxConsecutiveCorrect: bigint;
      }
    ],
    "view"
  >;

  getAccuracyRate: TypedContractMethod<[engine: AddressLike], [bigint], "view">;

  getAnalystTier: TypedContractMethod<[engine: AddressLike], [bigint], "view">;

  getDecayParameters: TypedContractMethod<
    [],
    [[bigint, bigint] & { decayRate: bigint; decayPeriod: bigint }],
    "view"
  >;

  getEngineInfo: TypedContractMethod<
    [engineAddress: AddressLike],
    [IReputationSystem.EngineInfoStructOutput],
    "view"
  >;

  getEngineMultiplier: TypedContractMethod<
    [engineType: BigNumberish],
    [bigint],
    "view"
  >;

  getEngineProfile: TypedContractMethod<
    [engine: AddressLike],
    [ReputationSystem.EngineProfileStructOutput],
    "view"
  >;

  getMinimumReputation: TypedContractMethod<[], [bigint], "view">;

  getReputation: TypedContractMethod<[engine: AddressLike], [bigint], "view">;

  getReputationHistory: TypedContractMethod<
    [engineAddress: AddressLike, limit: BigNumberish],
    [IReputationSystem.ReputationRecordStructOutput[]],
    "view"
  >;

  getReputationTier: TypedContractMethod<
    [tier: BigNumberish],
    [ReputationSystem.ReputationTierStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTopAnalysts: TypedContractMethod<
    [limit: BigNumberish],
    [string[]],
    "view"
  >;

  getTopEngines: TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { enginesList: string[]; reputations: bigint[] }],
    "view"
  >;

  getTotalAnalysts: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isEligibleEngine: TypedContractMethod<
    [engineAddress: AddressLike],
    [boolean],
    "view"
  >;

  isEligibleForTier: TypedContractMethod<
    [engine: AddressLike, requiredTier: BigNumberish],
    [boolean],
    "view"
  >;

  nextSubmissionId: TypedContractMethod<[], [bigint], "view">;

  penalizeEngine: TypedContractMethod<
    [engineAddress: AddressLike, penaltyAmount: BigNumberish, reason: string],
    [boolean],
    "nonpayable"
  >;

  reactivateEngine: TypedContractMethod<
    [engineAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  recordSubmission: TypedContractMethod<
    [
      engine: AddressLike,
      bountyId: BigNumberish,
      prediction: boolean,
      stakeAmount: BigNumberish,
      confidenceScore: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  registerEngine: TypedContractMethod<
    [engineAddress: AddressLike, engineType: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  reputationTiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        minReputation: bigint;
        maxStakeMultiplier: bigint;
        rewardBonus: bigint;
        tierName: string;
      }
    ],
    "view"
  >;

  resolveSubmission: TypedContractMethod<
    [submissionId: BigNumberish, actualResult: boolean],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rewardEngine: TypedContractMethod<
    [
      engineAddress: AddressLike,
      rewardAmount: BigNumberish,
      bountyId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submissions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint, bigint, boolean, bigint] & {
        engine: string;
        bountyId: bigint;
        prediction: boolean;
        actualResult: boolean;
        stakeAmount: bigint;
        timestamp: bigint;
        isResolved: boolean;
        confidenceScore: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalActiveEngines: TypedContractMethod<[], [bigint], "view">;

  updateReputation: TypedContractMethod<
    [engine: AddressLike, success: boolean],
    [void],
    "nonpayable"
  >;

  updateReputationForAnalysis: TypedContractMethod<
    [
      engineAddress: AddressLike,
      bountyId: BigNumberish,
      wasCorrect: boolean,
      stakeAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACCURACY_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BOUNTY_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CONSISTENCY_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECAY_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INITIAL_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SUBMISSIONS_FOR_RATING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PARTICIPATION_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeEngines"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "applyReputationDecay"
  ): TypedContractMethod<[engineAddress: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "applyReputationDecayAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateRequiredStake"
  ): TypedContractMethod<
    [engineAddress: AddressLike, baseStake: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateEngine"
  ): TypedContractMethod<[engineAddress: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "decayTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "engineIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "engineSubmissions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "engines"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        isRegistered: boolean;
        engineType: bigint;
        reputation: bigint;
        totalSubmissions: bigint;
        correctPredictions: bigint;
        lastActiveTimestamp: bigint;
        registrationTimestamp: bigint;
        isActive: boolean;
        falsePositives: bigint;
        falseNegatives: bigint;
        totalStakeAmount: bigint;
        totalRewards: bigint;
        consecutiveCorrect: bigint;
        maxConsecutiveCorrect: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccuracyRate"
  ): TypedContractMethod<[engine: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAnalystTier"
  ): TypedContractMethod<[engine: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDecayParameters"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { decayRate: bigint; decayPeriod: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEngineInfo"
  ): TypedContractMethod<
    [engineAddress: AddressLike],
    [IReputationSystem.EngineInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEngineMultiplier"
  ): TypedContractMethod<[engineType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEngineProfile"
  ): TypedContractMethod<
    [engine: AddressLike],
    [ReputationSystem.EngineProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinimumReputation"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[engine: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationHistory"
  ): TypedContractMethod<
    [engineAddress: AddressLike, limit: BigNumberish],
    [IReputationSystem.ReputationRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputationTier"
  ): TypedContractMethod<
    [tier: BigNumberish],
    [ReputationSystem.ReputationTierStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTopAnalysts"
  ): TypedContractMethod<[limit: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTopEngines"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]] & { enginesList: string[]; reputations: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalAnalysts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEligibleEngine"
  ): TypedContractMethod<[engineAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isEligibleForTier"
  ): TypedContractMethod<
    [engine: AddressLike, requiredTier: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextSubmissionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "penalizeEngine"
  ): TypedContractMethod<
    [engineAddress: AddressLike, penaltyAmount: BigNumberish, reason: string],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reactivateEngine"
  ): TypedContractMethod<[engineAddress: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "recordSubmission"
  ): TypedContractMethod<
    [
      engine: AddressLike,
      bountyId: BigNumberish,
      prediction: boolean,
      stakeAmount: BigNumberish,
      confidenceScore: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEngine"
  ): TypedContractMethod<
    [engineAddress: AddressLike, engineType: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputationTiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        minReputation: bigint;
        maxStakeMultiplier: bigint;
        rewardBonus: bigint;
        tierName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveSubmission"
  ): TypedContractMethod<
    [submissionId: BigNumberish, actualResult: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardEngine"
  ): TypedContractMethod<
    [
      engineAddress: AddressLike,
      rewardAmount: BigNumberish,
      bountyId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint, bigint, boolean, bigint] & {
        engine: string;
        bountyId: bigint;
        prediction: boolean;
        actualResult: boolean;
        stakeAmount: bigint;
        timestamp: bigint;
        isResolved: boolean;
        confidenceScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalActiveEngines"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [engine: AddressLike, success: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputationForAnalysis"
  ): TypedContractMethod<
    [
      engineAddress: AddressLike,
      bountyId: BigNumberish,
      wasCorrect: boolean,
      stakeAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "EnginePenalized"
  ): TypedContractEvent<
    EnginePenalizedEvent.InputTuple,
    EnginePenalizedEvent.OutputTuple,
    EnginePenalizedEvent.OutputObject
  >;
  getEvent(
    key: "EngineRegistered"
  ): TypedContractEvent<
    EngineRegisteredEvent.InputTuple,
    EngineRegisteredEvent.OutputTuple,
    EngineRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EngineRewarded"
  ): TypedContractEvent<
    EngineRewardedEvent.InputTuple,
    EngineRewardedEvent.OutputTuple,
    EngineRewardedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationDecayed"
  ): TypedContractEvent<
    ReputationDecayedEvent.InputTuple,
    ReputationDecayedEvent.OutputTuple,
    ReputationDecayedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionRecorded"
  ): TypedContractEvent<
    SubmissionRecordedEvent.InputTuple,
    SubmissionRecordedEvent.OutputTuple,
    SubmissionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionResolved"
  ): TypedContractEvent<
    SubmissionResolvedEvent.InputTuple,
    SubmissionResolvedEvent.OutputTuple,
    SubmissionResolvedEvent.OutputObject
  >;

  filters: {
    "EnginePenalized(address,uint256,string)": TypedContractEvent<
      EnginePenalizedEvent.InputTuple,
      EnginePenalizedEvent.OutputTuple,
      EnginePenalizedEvent.OutputObject
    >;
    EnginePenalized: TypedContractEvent<
      EnginePenalizedEvent.InputTuple,
      EnginePenalizedEvent.OutputTuple,
      EnginePenalizedEvent.OutputObject
    >;

    "EngineRegistered(address,uint8,uint256)": TypedContractEvent<
      EngineRegisteredEvent.InputTuple,
      EngineRegisteredEvent.OutputTuple,
      EngineRegisteredEvent.OutputObject
    >;
    EngineRegistered: TypedContractEvent<
      EngineRegisteredEvent.InputTuple,
      EngineRegisteredEvent.OutputTuple,
      EngineRegisteredEvent.OutputObject
    >;

    "EngineRewarded(address,uint256,uint256)": TypedContractEvent<
      EngineRewardedEvent.InputTuple,
      EngineRewardedEvent.OutputTuple,
      EngineRewardedEvent.OutputObject
    >;
    EngineRewarded: TypedContractEvent<
      EngineRewardedEvent.InputTuple,
      EngineRewardedEvent.OutputTuple,
      EngineRewardedEvent.OutputObject
    >;

    "ReputationDecayed(address,uint256)": TypedContractEvent<
      ReputationDecayedEvent.InputTuple,
      ReputationDecayedEvent.OutputTuple,
      ReputationDecayedEvent.OutputObject
    >;
    ReputationDecayed: TypedContractEvent<
      ReputationDecayedEvent.InputTuple,
      ReputationDecayedEvent.OutputTuple,
      ReputationDecayedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256,string)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SubmissionRecorded(uint256,address,uint256,bool,uint256)": TypedContractEvent<
      SubmissionRecordedEvent.InputTuple,
      SubmissionRecordedEvent.OutputTuple,
      SubmissionRecordedEvent.OutputObject
    >;
    SubmissionRecorded: TypedContractEvent<
      SubmissionRecordedEvent.InputTuple,
      SubmissionRecordedEvent.OutputTuple,
      SubmissionRecordedEvent.OutputObject
    >;

    "SubmissionResolved(uint256,bool,uint256)": TypedContractEvent<
      SubmissionResolvedEvent.InputTuple,
      SubmissionResolvedEvent.OutputTuple,
      SubmissionResolvedEvent.OutputObject
    >;
    SubmissionResolved: TypedContractEvent<
      SubmissionResolvedEvent.InputTuple,
      SubmissionResolvedEvent.OutputTuple,
      SubmissionResolvedEvent.OutputObject
    >;
  };
}
