apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-api-gateway
  namespace: nexus-security
  labels:
    app.kubernetes.io/name: nexus-security
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: nexus-security-platform
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-security
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus-security
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/part-of: nexus-security-platform
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: nexus-security-sa
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      
      # Init container for database migrations
      initContainers:
      - name: migrate-db
        image: nexus-security/api-gateway:latest
        command: ["./migrate"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nexus-database-secret
              key: database_url
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      
      containers:
      - name: api-gateway
        image: nexus-security/api-gateway:latest
        imagePullPolicy: IfNotPresent
        
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        
        env:
        # Database configuration
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nexus-database-secret
              key: database_url
        - name: DATABASE_HOST
          value: "nexus-postgres-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "nexus_security"
        
        # Redis configuration
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: nexus-redis-secret
              key: redis_url
        - name: REDIS_HOST
          value: "nexus-redis-service"
        - name: REDIS_PORT
          value: "6379"
        
        # JWT secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nexus-auth-secret
              key: jwt_secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: nexus-auth-secret
              key: jwt_refresh_secret
        
        # Blockchain configuration
        - name: ETHEREUM_RPC_URL
          valueFrom:
            secretKeyRef:
              name: nexus-blockchain-secret
              key: rpc_url
        - name: CONTRACT_ADDRESS_BOUNTY
          valueFrom:
            configMapKeyRef:
              name: nexus-blockchain-config
              key: bounty_contract_address
        - name: CONTRACT_ADDRESS_TOKEN
          valueFrom:
            configMapKeyRef:
              name: nexus-blockchain-config
              key: token_contract_address
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: nexus-blockchain-secret
              key: private_key
        
        # Application configuration
        - name: RUST_LOG
          value: "info,nexus_api_gateway=debug"
        - name: ENVIRONMENT
          value: "production"
        - name: CONFIG_PATH
          value: "/app/config"
        
        # Service discovery
        - name: ANALYSIS_ENGINE_URL
          value: "http://nexus-analysis-service:8080"
        - name: BOUNTY_MANAGER_URL
          value: "http://nexus-bounty-service:8081"
        - name: ENGINE_MANAGER_URL
          value: "http://nexus-engine-service:8082"
        - name: BLOCKCHAIN_SERVICE_URL
          value: "http://nexus-blockchain-service:8083"
        - name: AUTH_SERVICE_URL
          value: "http://nexus-auth-service:8084"
        - name: REPUTATION_SERVICE_URL
          value: "http://nexus-reputation-service:8085"
        
        # Performance tuning
        - name: TOKIO_WORKER_THREADS
          value: "4"
        - name: MAX_BLOCKING_THREADS
          value: "16"
        
        # Security
        - name: ALLOWED_ORIGINS
          value: "https://nexus-security.com,https://app.nexus-security.com"
        
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: app-cache
          mountPath: /app/cache
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        # Startup probe for slow initialization
        startupProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        # Resource limits
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
      
      volumes:
      - name: config-volume
        configMap:
          name: nexus-api-gateway-config
          defaultMode: 0644
      - name: tmp-volume
        emptyDir:
          sizeLimit: 1Gi
      - name: app-cache
        emptyDir:
          sizeLimit: 2Gi
      
      # Pod affinity for better distribution
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - api-gateway
              topologyKey: kubernetes.io/hostname
      
      # Node selection
      nodeSelector:
        kubernetes.io/arch: amd64
      
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexus-api-gateway-hpa
  namespace: nexus-security
  labels:
    app.kubernetes.io/name: nexus-security
    app.kubernetes.io/component: api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexus-api-gateway
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nexus-api-gateway-pdb
  namespace: nexus-security
  labels:
    app.kubernetes.io/name: nexus-security
    app.kubernetes.io/component: api-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-security
      app.kubernetes.io/component: api-gateway